// Code generated by generator; DO NOT EDIT.

package db

import (
	"database/sql"

	"entgo.io/ent"
	entsql "entgo.io/ent/dialect/sql"
	"github.com/Masterminds/squirrel"
	"github.com/cockroachdb/pebble"
	badger "github.com/dgraph-io/badger/v4"
	goqu "github.com/doug-martin/goqu/v9"
	elasticsearch "github.com/elastic/go-elasticsearch/v8"
	"github.com/georgysavva/scany/v2/pgxscan"
	gormcaches "github.com/go-gorm/caches/v4"
	mysql "github.com/go-sql-driver/mysql"
	sqlbuilder "github.com/huandu/go-sqlbuilder"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jmoiron/sqlx"
	pq "github.com/lib/pq"
	sqlite3 "github.com/mattn/go-sqlite3"
	common "github.com/numtide/go2nix/torture/internal/common"
	goose "github.com/pressly/goose/v3"
	redis "github.com/redis/go-redis/v9"
	"github.com/uptrace/bun"
	clientv3 "go.etcd.io/etcd/client/v3"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	gormpostgres "gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ *pgx.Conn
	_ = redis.Options{}
	var _ *mongo.Client
	_ = bson.D{}
	_ = mysql.Config{}
	var _ *sql.DB
	var _ *sqlx.DB
	_ = clientv3.Config{}
	_ = badger.DefaultOptions("")
	var _ *pebble.DB
	_ = elasticsearch.Config{}
	_ = sqlite3.ErrNo(0)
	_ = pq.ErrSSLNotSupported
	var _ *bun.DB
	_ = goose.Up
	var _ *gorm.DB
	_ = gormpostgres.Open
	var _ ent.Value
	var _ *entsql.Driver
	_ = gormcaches.Config{}
	_ = sqlbuilder.Select("")
	_ = goqu.Dialect("")
	_ = squirrel.Select("")
	_ = pgxscan.Select
	var _ *pgxpool.Pool
	return nil
}
