// Code generated by generator; DO NOT EDIT.

package aws

import (
	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/apigateway"
	"github.com/aws/aws-sdk-go-v2/service/athena"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	"github.com/aws/aws-sdk-go-v2/service/cloudfront"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ecr"
	"github.com/aws/aws-sdk-go-v2/service/efs"
	"github.com/aws/aws-sdk-go-v2/service/eks"
	"github.com/aws/aws-sdk-go-v2/service/elasticache"
	"github.com/aws/aws-sdk-go-v2/service/elasticsearchservice"
	"github.com/aws/aws-sdk-go-v2/service/emr"
	"github.com/aws/aws-sdk-go-v2/service/firehose"
	"github.com/aws/aws-sdk-go-v2/service/glue"
	"github.com/aws/aws-sdk-go-v2/service/iam"
	"github.com/aws/aws-sdk-go-v2/service/kinesis"
	"github.com/aws/aws-sdk-go-v2/service/kms"
	"github.com/aws/aws-sdk-go-v2/service/lambda"
	"github.com/aws/aws-sdk-go-v2/service/rds"
	"github.com/aws/aws-sdk-go-v2/service/redshift"
	"github.com/aws/aws-sdk-go-v2/service/route53"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/sagemaker"
	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"github.com/aws/aws-sdk-go-v2/service/ses"
	"github.com/aws/aws-sdk-go-v2/service/sfn"
	"github.com/aws/aws-sdk-go-v2/service/sns"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"github.com/aws/aws-sdk-go-v2/service/waf"
	common "github.com/numtide/go2nix/torture/internal/common"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	_ = aws.String("x")
	_ = awsconfig.WithRegion("us-east-1")
	var _ *s3.Client
	var _ *sts.Client
	var _ *eks.Client
	var _ *dynamodb.Client
	var _ *sqs.Client
	var _ *lambda.Client
	var _ *ec2.Client
	var _ *iam.Client
	var _ *cloudwatch.Client
	var _ *sns.Client
	var _ *secretsmanager.Client
	var _ *kms.Client
	var _ *route53.Client
	var _ *rds.Client
	var _ *elasticache.Client
	var _ *kinesis.Client
	var _ *ses.Client
	var _ *ssm.Client
	var _ *ecr.Client
	var _ *efs.Client
	var _ *sfn.Client
	var _ *cloudformation.Client
	var _ *emr.Client
	var _ *glue.Client
	var _ *athena.Client
	var _ *redshift.Client
	var _ *apigateway.Client
	var _ *cognitoidentityprovider.Client
	var _ *cloudfront.Client
	var _ *waf.Client
	var _ *elasticsearchservice.Client
	var _ *firehose.Client
	var _ *sagemaker.Client
	return nil
}
