// Code generated by generator; DO NOT EDIT.

package observability

import (
	statsd "github.com/DataDog/datadog-go/v5/statsd"
	gogoproto "github.com/gogo/protobuf/proto"
	pyroscope "github.com/grafana/pyroscope-go"
	common "github.com/numtide/go2nix/torture/internal/common"
	"github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/common/model"
	promhist "github.com/prometheus/prometheus/model/histogram"
	promlabels "github.com/prometheus/prometheus/model/labels"
	"github.com/sirupsen/logrus"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	otelprom "go.opentelemetry.io/otel/exporters/prometheus"
	otelmetric "go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	oteltrace "go.opentelemetry.io/otel/trace"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"log/slog"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ prometheus.Collector
	_ = promauto.With(nil)
	_ = otel.GetTracerProvider()
	var _ oteltrace.Tracer
	var _ otelmetric.Meter
	_ = attribute.String("k", "v")
	var _ otlptrace.Exporter
	var _ *sdktrace.TracerProvider
	_ = zap.NewNop()
	_ = logrus.Fields{}
	_ = slog.Default()
	_ = zapcore.DebugLevel
	_ = pyroscope.Config{}
	_ = statsd.Option(nil)
	_ = model.LabelName("")
	var _ *otelprom.Exporter
	var _ = otlpmetricgrpc.New
	var _ = otlptracegrpc.New
	var _ *sdkmetric.MeterProvider
	var _ = otelhttp.NewHandler
	var _ = otelgrpc.NewClientHandler
	var _ *ottl.Parser[any]
	_ = promlabels.Labels{}
	var _ gogoproto.Message
	_ = promhist.FloatHistogram{}
	return nil
}
