// Code generated by generator; DO NOT EDIT.

package gcp

import (
	"cloud.google.com/go/bigquery"
	"cloud.google.com/go/bigtable"
	gcemetadata "cloud.google.com/go/compute/metadata"
	"cloud.google.com/go/datastore"
	"cloud.google.com/go/firestore"
	cloudiam "cloud.google.com/go/iam"
	"cloud.google.com/go/logging"
	"cloud.google.com/go/pubsub"
	"cloud.google.com/go/spanner"
	"cloud.google.com/go/storage"
	common "github.com/numtide/go2nix/torture/internal/common"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ *storage.Client
	var _ *bigquery.Client
	var _ *pubsub.Client
	var _ *firestore.Client
	var _ *spanner.Client
	var _ *logging.Client
	var _ *datastore.Client
	var _ *bigtable.Client
	_ = gcemetadata.OnGCE()
	var _ *cloudiam.Handle
	return nil
}
