# Test: mkGoPackageSet on a minimal lockfile containing just google/uuid.
let
  pkgs = import <nixpkgs> { };
  go2nixLib = import ../lib.nix { };
  go = pkgs.go;
  go2nix = import ../go/go2nix/package.nix { inherit pkgs; };

  # Use the app-partial lockfile generated by go2nix.
  packageSet = go2nixLib.mkGoPackageSet {
    goLock = /tmp/test-lockfile.toml;
    inherit go go2nix pkgs;
  };

  # Build ALL packages from the lockfile.
  # Use flat names (slashes → dashes) to avoid path conflicts in linkFarm.
  allPackages = pkgs.linkFarm "all-go-packages" (
    builtins.map (name: {
      name = builtins.replaceStrings [ "/" ] [ "-" ] name;
      path = packageSet.${name};
    }) (builtins.attrNames packageSet)
  );

in
allPackages
