// Code generated by generator; DO NOT EDIT.

package conflicta

import (
	"database/sql"
	"net/http"

	"github.com/cockroachdb/pebble"
	badger "github.com/dgraph-io/badger/v4"
	elasticsearch "github.com/elastic/go-elasticsearch/v8"
	"github.com/gin-gonic/gin"
	chi "github.com/go-chi/chi/v5"
	validator "github.com/go-playground/validator/v10"
	resty "github.com/go-resty/resty/v2"
	mysql "github.com/go-sql-driver/mysql"
	fiber "github.com/gofiber/fiber/v2"
	"github.com/gorilla/csrf"
	"github.com/gorilla/mux"
	"github.com/gorilla/sessions"
	"github.com/gorilla/websocket"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jmoiron/sqlx"
	"github.com/julienschmidt/httprouter"
	echo "github.com/labstack/echo/v4"
	pq "github.com/lib/pq"
	sqlite3 "github.com/mattn/go-sqlite3"
	common "github.com/numtide/go2nix/torture/internal/common"
	goose "github.com/pressly/goose/v3"
	redis "github.com/redis/go-redis/v9"
	"github.com/rs/cors"
	"github.com/rs/zerolog"
	"github.com/uptrace/bun"
	"github.com/valyala/fasthttp"
	clientv3 "go.etcd.io/etcd/client/v3"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ *gin.Engine
	var _ *echo.Echo
	var _ *fiber.App
	var _ http.Handler
	_ = mux.NewRouter()
	_ = websocket.Upgrader{}
	_ = chi.NewRouter()
	_ = httprouter.New()
	_ = cors.Options{}
	_ = validator.New()
	var _ sessions.Store
	_ = csrf.Protect
	_ = zerolog.Logger{}
	_ = resty.New()
	var _ *fasthttp.Server
	var _ *pgx.Conn
	_ = redis.Options{}
	var _ *mongo.Client
	_ = bson.D{}
	_ = mysql.Config{}
	var _ *sql.DB
	var _ *sqlx.DB
	_ = clientv3.Config{}
	_ = badger.DefaultOptions("")
	var _ *pebble.DB
	_ = elasticsearch.Config{}
	_ = sqlite3.SQLiteDriver{}
	_ = pq.ErrSSLNotSupported
	var _ *bun.DB
	_ = goose.Up
	return nil
}
