// Code generated by generator; DO NOT EDIT.

package data

import (
	clickhouse "github.com/ClickHouse/clickhouse-go/v2"
	bigcache "github.com/allegro/bigcache/v3"
	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/parquet"
	"github.com/coocood/freecache"
	redisrate "github.com/go-redis/redis_rate/v10"
	influxdb "github.com/influxdata/influxdb-client-go/v2"
	goavro "github.com/linkedin/goavro/v2"
	common "github.com/numtide/go2nix/torture/internal/common"
	db "github.com/numtide/go2nix/torture/internal/db"
	gocache "github.com/patrickmn/go-cache"
	parquetreader "github.com/xitongsys/parquet-go/reader"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	if err := db.Run(); err != nil {
		return err
	}
	var _ arrow.DataType
	var _ = parquet.Types
	var _ *goavro.Codec
	var _ *parquetreader.ParquetReader
	var _ influxdb.Client
	var _ clickhouse.Conn
	var _ *redisrate.Limiter
	_ = bigcache.DefaultConfig(0)
	_ = gocache.New(0, 0)
	_ = freecache.NewCache(1024)
	return nil
}
