// Code generated by generator; DO NOT EDIT.

package web

import (
	sprig "github.com/Masterminds/sprig/v3"
	templ "github.com/a-h/templ"
	pongo2 "github.com/flosch/pongo2/v6"
	"github.com/gin-gonic/gin"
	chi "github.com/go-chi/chi/v5"
	validator "github.com/go-playground/validator/v10"
	resty "github.com/go-resty/resty/v2"
	fiber "github.com/gofiber/fiber/v2"
	"github.com/gorilla/csrf"
	"github.com/gorilla/mux"
	"github.com/gorilla/sessions"
	"github.com/gorilla/websocket"
	"github.com/julienschmidt/httprouter"
	echo "github.com/labstack/echo/v4"
	"github.com/magefile/mage/mg"
	common "github.com/numtide/go2nix/torture/internal/common"
	db "github.com/numtide/go2nix/torture/internal/db"
	"github.com/rs/cors"
	"github.com/rs/zerolog"
	"github.com/valyala/fasthttp"
	"github.com/valyala/quicktemplate"
	htmltemplate "html/template"
	"net/http"
	texttemplate "text/template"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	if err := db.Run(); err != nil {
		return err
	}
	var _ *gin.Engine
	var _ *echo.Echo
	var _ *fiber.App
	var _ http.Handler
	_ = mux.NewRouter()
	_ = websocket.Upgrader{}
	_ = chi.NewRouter()
	_ = httprouter.New()
	_ = cors.Options{}
	_ = validator.New()
	var _ sessions.Store
	var _ = csrf.Protect
	_ = zerolog.Logger{}
	_ = resty.New()
	var _ *fasthttp.Server
	var _ *htmltemplate.Template
	var _ *texttemplate.Template
	_ = sprig.FuncMap()
	var _ *pongo2.Template
	var _ *quicktemplate.Writer
	var _ templ.Component
	_ = mg.Verbose()
	return nil
}
