// Code generated by generator; DO NOT EDIT.

package testinglib

import (
	sqlmock "github.com/DATA-DOG/go-sqlmock"
	gofakeit "github.com/brianvoe/gofakeit/v7"
	gomock "github.com/golang/mock/gomock"
	ghapi "github.com/google/go-github/v68/github"
	"github.com/h2non/gock"
	"github.com/jarcoal/httpmock"
	milvusclient "github.com/milvus-io/milvus-sdk-go/v2/client"
	common "github.com/numtide/go2nix/torture/internal/common"
	ollamaapi "github.com/ollama/ollama/api"
	ginkgo "github.com/onsi/ginkgo/v2"
	"github.com/onsi/gomega"
	pgvector "github.com/pgvector/pgvector-go"
	openai "github.com/sashabaranov/go-openai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	langchainllms "github.com/tmc/langchaingo/llms"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ = assert.Equal
	var _ = require.Equal
	var _ = ginkgo.Describe
	var _ = gomega.Expect
	var _ = httpmock.Activate
	var _ = sqlmock.New
	var _ *gomock.Controller
	_ = gofakeit.Name()
	_ = ghapi.NewClient(nil)
	var _ = gock.New
	_ = openai.ChatCompletionRequest{}
	_ = ollamaapi.ChatRequest{}
	_ = pgvector.NewVector(nil)
	var _ langchainllms.Model
	var _ milvusclient.Client
	return nil
}
