// Code generated by generator; DO NOT EDIT.

package networking

import (
	"github.com/IBM/sarama"
	gogit "github.com/go-git/go-git/v5"
	ghwebhooks "github.com/go-playground/webhooks/v6/github"
	"github.com/hashicorp/memberlist"
	"github.com/hashicorp/raft"
	common "github.com/numtide/go2nix/torture/internal/common"
	webrtc "github.com/pion/webrtc/v4"
	quic "github.com/quic-go/quic-go"
	"github.com/traefik/yaegi/interp"
	"github.com/twmb/franz-go/pkg/kgo"
	nhws "nhooyr.io/websocket"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ *gogit.Repository
	_ = memberlist.DefaultLANConfig()
	var _ raft.FSM
	_ = interp.New(interp.Options{})
	var _ = ghwebhooks.New
	var _ *nhws.Conn
	_ = sarama.NewConfig()
	var _ *kgo.Client
	var _ *quic.Config
	_ = webrtc.Configuration{}
	return nil
}
