// Code generated by generator; DO NOT EDIT.

package k8s

import (
	common "github.com/numtide/go2nix/torture/internal/common"
	appsv1 "k8s.io/api/apps/v1"
	autoscalingv2 "k8s.io/api/autoscaling/v2"
	batchv1 "k8s.io/api/batch/v1"
	certificatesv1 "k8s.io/api/certificates/v1"
	coordinationv1 "k8s.io/api/coordination/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	policyv1 "k8s.io/api/policy/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	storagev1 "k8s.io/api/storage/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime"
	k8stypes "k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	k8scache "k8s.io/client-go/tools/cache"
	"k8s.io/client-go/tools/clientcmd"
	ctrl "sigs.k8s.io/controller-runtime"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ kubernetes.Interface
	_ = corev1.Pod{}
	_ = appsv1.Deployment{}
	_ = metav1.ObjectMeta{}
	var _ runtime.Object
	_ = k8stypes.NamespacedName{}
	_ = rest.Config{}
	_ = clientcmd.NewDefaultClientConfigLoadingRules
	_ = ctrl.Log
	var _ ctrlclient.Client
	var _ k8scache.Store
	_ = labels.Everything()
	_ = batchv1.Job{}
	_ = rbacv1.ClusterRole{}
	_ = networkingv1.Ingress{}
	_ = storagev1.StorageClass{}
	_ = autoscalingv2.HorizontalPodAutoscaler{}
	_ = policyv1.PodDisruptionBudget{}
	_ = coordinationv1.Lease{}
	_ = certificatesv1.CertificateSigningRequest{}
	_ = apiextensionsv1.CustomResourceDefinition{}
	var _ dynamic.Interface
	return nil
}
