// Code generated by generator; DO NOT EDIT.

package azure

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos"
	"github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs"
	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v6"
	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v6"
	"github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	common "github.com/numtide/go2nix/torture/internal/common"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ azcore.TokenCredential
	var _ *azidentity.DefaultAzureCredential
	var _ *azblob.Client
	var _ *azeventhubs.ProducerClient
	var _ *azcosmos.Client
	var _ *azsecrets.Client
	var _ *armcompute.VirtualMachinesClient
	var _ *armnetwork.InterfacesClient
	return nil
}
