// Package lockfile handles reading and writing go2nix TOML lockfiles.
package lockfile

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/BurntSushi/toml"
)

// Lockfile holds the parsed go2nix v2 lockfile.
type Lockfile struct {
	Mod     map[string]string              `toml:"mod"`
	Replace map[string]string              `toml:"replace,omitempty"`
	Pkg     map[string]map[string][]string `toml:"pkg,omitempty"`
}

// Read reads a lockfile from path. Returns an empty lockfile if the file
// does not exist.
func Read(path string) (*Lockfile, error) {
	lf := &Lockfile{
		Mod:     map[string]string{},
		Replace: map[string]string{},
		Pkg:     map[string]map[string][]string{},
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return lf, nil
	}
	if err != nil {
		return nil, err
	}
	md, err := toml.Decode(string(data), lf)
	if err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		return nil, fmt.Errorf("parsing %s: unknown keys: %v", path, undecoded)
	}
	return lf, nil
}

// Write writes the lockfile to path with the given header.
func (lf *Lockfile) Write(path, header string) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	if err := toml.NewEncoder(&buf).Encode(lf); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// Header is the standard lockfile header.
const Header = `# go2nix lockfile v2. Generated by go2nix. Do not edit.

`

// Gomod2nixMod holds a single module entry in the gomod2nix (v1) lockfile format.
type Gomod2nixMod struct {
	Version  string `toml:"version"`
	Hash     string `toml:"hash"`
	Replaced string `toml:"replaced,omitempty"`
}

// Gomod2nixLockfile is the v1-style lockfile consumed by the gomod2nix Nix builder.
// Module values are attrsets (version + hash + optional replaced) instead of
// plain hash strings.
type Gomod2nixLockfile struct {
	Mod map[string]Gomod2nixMod `toml:"mod"`
}

// Gomod2nixHeader is the header for gomod2nix-style lockfiles.
const Gomod2nixHeader = `# go2nix lockfile (gomod2nix format). Generated by go2nix. Do not edit.

`

// Write writes the gomod2nix lockfile to path with the given header.
func (lf *Gomod2nixLockfile) Write(path, header string) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	if err := toml.NewEncoder(&buf).Encode(lf); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// ToGomod2nix converts a v2 lockfile to the gomod2nix (v1) format.
// Version is extracted from the composite key (path@version).
func (lf *Lockfile) ToGomod2nix() *Gomod2nixLockfile {
	result := &Gomod2nixLockfile{
		Mod: make(map[string]Gomod2nixMod, len(lf.Mod)),
	}
	for key, hash := range lf.Mod {
		_, version, _ := strings.Cut(key, "@")
		mod := Gomod2nixMod{
			Version: version,
			Hash:    hash,
		}
		if r, ok := lf.Replace[key]; ok {
			mod.Replaced = r
		}
		result.Mod[key] = mod
	}
	return result
}
