// Package lockfile handles reading and writing go2nix TOML lockfiles.
package lockfile

import (
	"bytes"
	"errors"
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

// ModEntry is one module in the lockfile [mod.*] section.
type ModEntry struct {
	Version  string `toml:"version"`
	Hash     string `toml:"hash"`
	Replaced string `toml:"replaced,omitempty"`
	NumPkgs  int    `toml:"num_pkgs"`
}

// PkgEntry is one package in the lockfile [pkg.*] section.
type PkgEntry struct {
	Module  string   `toml:"module"`
	Imports []string `toml:"imports,omitempty"`
}

// Lockfile holds the parsed go2nix lockfile.
type Lockfile struct {
	Mod map[string]ModEntry `toml:"mod"`
	Pkg map[string]PkgEntry `toml:"pkg"`
}

// Read reads a lockfile from path. Returns an empty lockfile if the file
// does not exist.
func Read(path string) (*Lockfile, error) {
	lf := &Lockfile{Mod: map[string]ModEntry{}, Pkg: map[string]PkgEntry{}}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return lf, nil
	}
	if err != nil {
		return nil, err
	}
	md, err := toml.Decode(string(data), lf)
	if err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		return nil, fmt.Errorf("parsing %s: unknown keys: %v", path, undecoded)
	}
	return lf, nil
}

// Write writes the lockfile to path with the given header.
func (lf *Lockfile) Write(path, header string) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	if err := toml.NewEncoder(&buf).Encode(lf); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// Header is the standard lockfile header.
const Header = `# go2nix lockfile — package-level build graph.
# [mod.*]: module@version -> NAR hash (for fetchModuleProxy FODs)
# [pkg.*]: import path -> module + direct imports (for per-package derivations)
# Generated by go2nix. Do not edit.

`
