// Package lockfile handles reading and writing go2nix TOML lockfiles.
package lockfile

import (
	"bytes"
	"errors"
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

// Lockfile holds the parsed go2nix v2 lockfile.
type Lockfile struct {
	Mod     map[string]string              `toml:"mod"`
	Replace map[string]string              `toml:"replace,omitempty"`
	Pkg     map[string]map[string][]string `toml:"pkg,omitempty"`
}

// Read reads a lockfile from path. Returns an empty lockfile if the file
// does not exist.
func Read(path string) (*Lockfile, error) {
	lf := &Lockfile{
		Mod:     map[string]string{},
		Replace: map[string]string{},
		Pkg:     map[string]map[string][]string{},
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return lf, nil
	}
	if err != nil {
		return nil, err
	}
	md, err := toml.Decode(string(data), lf)
	if err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		return nil, fmt.Errorf("parsing %s: unknown keys: %v", path, undecoded)
	}
	return lf, nil
}

// Write writes the lockfile to path with the given header.
func (lf *Lockfile) Write(path, header string) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	if err := toml.NewEncoder(&buf).Encode(lf); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// Header is the standard lockfile header.
const Header = `# go2nix lockfile v2. Generated by go2nix. Do not edit.

`
