//go:build integration

package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// These tests shell out to `go` and `nix`. They're the only real verification
// that collectModules behaves correctly, since its contract is entirely about
// external-tool output. Run with -short to skip.

func requireTool(t *testing.T, name string) {
	t.Helper()
	if _, err := exec.LookPath(name); err != nil {
		t.Skipf("%s not on PATH", name)
	}
}

// writeModule sets up a tiny Go module in a temp directory and returns its path.
// A go.sum is generated by running `go mod download` (which the test under
// observation also needs).
func writeModule(t *testing.T, goMod, mainGo string) string {
	t.Helper()
	dir := t.TempDir()
	write := func(name, content string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", goMod)
	write("main.go", mainGo)
	// Populate go.sum. Use `go mod tidy` not `go mod download -mod=mod`:
	// the latter modifies go.mod in-place, which defeats tests that want to
	// observe an untidy go.mod.
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy (setup): %v\n%s", err, out)
	}
	return dir
}

func TestCollectModulesTidy(t *testing.T) {
	if testing.Short() {
		t.Skip("requires network + go toolchain")
	}
	requireTool(t, "go")

	dir := writeModule(t, `module tidy-test
go 1.23
require golang.org/x/sync v0.11.0
`, `package main
import _ "golang.org/x/sync/errgroup"
func main() {}
`)

	mods, err := collectModules(dir)
	if err != nil {
		t.Fatalf("collectModules: %v", err)
	}
	if len(mods) != 1 {
		t.Fatalf("want 1 module, got %d: %+v", len(mods), mods)
	}
	if got := mods[0].key; got != "golang.org/x/sync@v0.11.0" {
		t.Errorf("key = %q, want golang.org/x/sync@v0.11.0", got)
	}
	if mods[0].replaced() != "" {
		t.Errorf("replaced() = %q, want empty", mods[0].replaced())
	}
}

func TestCollectModulesUntidy(t *testing.T) {
	if testing.Short() {
		t.Skip("requires network + go toolchain")
	}
	requireTool(t, "go")

	// x/tools v0.30.0 requires x/mod >= v0.23.0. We'll start with a TIDY
	// go.mod (so go.sum has the right entries), then manually lower x/mod in
	// go.mod to make it untidy. writeModule's `go mod tidy` would otherwise
	// fix the very thing we're testing.
	dir := writeModule(t, `module untidy-test
go 1.23
require golang.org/x/tools v0.30.0
`, `package main
import _ "golang.org/x/tools/go/packages"
func main() {}
`)

	// Now break go.mod: lower an indirect dep below what MVS will pick.
	goModPath := filepath.Join(dir, "go.mod")
	tidy, err := os.ReadFile(goModPath) //nolint:gosec
	if err != nil {
		t.Fatal(err)
	}
	// go mod tidy recorded x/mod at MVS version; replace with v0.20.0.
	untidy := strings.Replace(string(tidy), "golang.org/x/mod v0.23.0", "golang.org/x/mod v0.20.0", 1)
	if untidy == string(tidy) {
		t.Skipf("tidy go.mod doesn't contain x/mod v0.23.0; test assumptions stale:\n%s", tidy)
	}
	if err := os.WriteFile(goModPath, []byte(untidy), 0o600); err != nil {
		t.Fatal(err)
	}
	// go.sum needs an entry for the lower version too, or `go mod download`
	// will fail on a checksum mismatch before we get to the tidiness check.
	cmd := exec.Command("go", "mod", "download", "golang.org/x/mod@v0.20.0")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod download v0.20.0 (setup): %v\n%s", err, out)
	}

	_, err = collectModules(dir)
	if err == nil {
		t.Fatalf("collectModules succeeded on untidy go.mod; want error")
	}
	if !strings.Contains(err.Error(), "not tidy") {
		t.Errorf("error = %q, want mention of 'not tidy'", err)
	}
	if !strings.Contains(err.Error(), "golang.org/x/mod") {
		t.Errorf("error = %q, want mention of the untidy module path", err)
	}
}

func TestCollectModulesLocalReplace(t *testing.T) {
	if testing.Short() {
		t.Skip("requires go toolchain")
	}
	requireTool(t, "go")

	parent := t.TempDir()
	// The replaced-to local module.
	localDir := filepath.Join(parent, "local")
	if err := os.MkdirAll(localDir, 0o755); err != nil {
		t.Fatal(err)
	}
	write := func(path, content string) {
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write(filepath.Join(localDir, "go.mod"), "module example.com/local\ngo 1.23\n")
	write(filepath.Join(localDir, "local.go"), "package local\n")

	// The main module, with a local replace + a real dep.
	mainDir := filepath.Join(parent, "main")
	if err := os.MkdirAll(mainDir, 0o755); err != nil {
		t.Fatal(err)
	}
	write(filepath.Join(mainDir, "go.mod"), `module localrepl-test
go 1.23
require (
	example.com/local v0.0.0-00010101000000-000000000000
	golang.org/x/sync v0.11.0
)
replace example.com/local => ../local
`)
	write(filepath.Join(mainDir, "main.go"), `package main
import (
	_ "example.com/local"
	_ "golang.org/x/sync/errgroup"
)
func main() {}
`)
	cmd := exec.Command("go", "mod", "download")
	cmd.Dir = mainDir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod download (setup): %v\n%s", err, out)
	}

	mods, err := collectModules(mainDir)
	if err != nil {
		t.Fatalf("collectModules: %v", err)
	}
	// Only the non-local dep should be present.
	if len(mods) != 1 {
		t.Fatalf("want 1 module, got %d: %+v", len(mods), mods)
	}
	if mods[0].key != "golang.org/x/sync@v0.11.0" {
		t.Errorf("key = %q, want golang.org/x/sync@v0.11.0", mods[0].key)
	}
	// Crucially: the local replace must NOT have triggered the tidiness check
	// even though the pseudo-version in require doesn't match anything.
}

func TestGenerateEndToEnd(t *testing.T) {
	if testing.Short() {
		t.Skip("requires network + go + nix")
	}
	requireTool(t, "go")
	requireTool(t, "nix")

	dir := writeModule(t, `module e2e-test
go 1.23
require golang.org/x/sync v0.11.0
`, `package main
import _ "golang.org/x/sync/errgroup"
func main() {}
`)

	lockPath := filepath.Join(t.TempDir(), "lock.toml")

	// Cold run: should hash 1 module.
	if err := generate([]string{dir}, lockPath, 4); err != nil {
		t.Fatalf("generate (cold): %v", err)
	}
	lf, err := readLockfile(lockPath)
	if err != nil {
		t.Fatalf("readLockfile: %v", err)
	}
	if len(lf.Mod) != 1 {
		t.Fatalf("want 1 lockfile entry, got %d", len(lf.Mod))
	}
	entry, ok := lf.Mod["golang.org/x/sync@v0.11.0"]
	if !ok {
		t.Fatalf("entry for x/sync@v0.11.0 missing; got keys: %v", keys(lf.Mod))
	}
	if !strings.HasPrefix(entry.Hash, "sha256-") {
		t.Errorf("hash = %q, want SRI sha256-...", entry.Hash)
	}

	// Warm run: identical output.
	data1, _ := os.ReadFile(lockPath) //nolint:gosec
	if err := generate([]string{dir}, lockPath, 4); err != nil {
		t.Fatalf("generate (warm): %v", err)
	}
	data2, _ := os.ReadFile(lockPath) //nolint:gosec
	if string(data1) != string(data2) {
		t.Errorf("warm run changed output")
	}
}

func keys[K comparable, V any](m map[K]V) []K {
	out := make([]K, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
