// Code generated by generator; DO NOT EDIT.

package cryptolib

import (
	"crypto/aes"
	"crypto/ed25519"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"

	casbin "github.com/casbin/casbin/v2"
	"github.com/cloudflare/circl/sign/ed448"
	"github.com/coreos/go-oidc/v3/oidc"
	ldap "github.com/go-ldap/ldap/v3"
	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/lestrrat-go/jwx/v2/jws"
	jwxjwt "github.com/lestrrat-go/jwx/v2/jwt"
	"github.com/mikespook/gorbac"
	common "github.com/numtide/go2nix/torture/internal/common"
	"golang.org/x/crypto/argon2"
	"golang.org/x/crypto/bcrypt"
	"golang.org/x/crypto/chacha20poly1305"
	naclbox "golang.org/x/crypto/nacl/box"
	"golang.org/x/crypto/ssh"
	"golang.org/x/oauth2"
	google "golang.org/x/oauth2/google"
)

// Run exercises imported packages.
func Run() error {
	if err := common.Run(); err != nil {
		return err
	}
	var _ ssh.Signer
	_ = bcrypt.MinCost
	_ = jwt.SigningMethodHS256
	_ = tls.Config{}
	var _ ed25519.PublicKey
	_ = sha256.New()
	_ = rand.Reader
	var _ ed448.PublicKey
	_ = argon2.IDKey
	_ = naclbox.Overhead
	_ = chacha20poly1305.KeySize
	_ = hmac.New
	_ = aes.BlockSize
	_ = oauth2.Token{}
	var _ *google.Credentials
	var _ *oidc.Provider
	var _ *casbin.Enforcer
	var _ *ldap.Conn
	_ = gorbac.New()
	var _ jwxjwt.Token
	var _ *jws.Message
	return nil
}
