// Code generated by generator; DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	aws "github.com/numtide/go2nix/torture/internal/aws"
	azure "github.com/numtide/go2nix/torture/internal/azure"
	common "github.com/numtide/go2nix/torture/internal/common"
	conflicta "github.com/numtide/go2nix/torture/internal/conflict-a"
	conflictb "github.com/numtide/go2nix/torture/internal/conflict-b"
	cryptolib "github.com/numtide/go2nix/torture/internal/crypto"
	data "github.com/numtide/go2nix/torture/internal/data"
	db "github.com/numtide/go2nix/torture/internal/db"
	gcp "github.com/numtide/go2nix/torture/internal/gcp"
	k8s "github.com/numtide/go2nix/torture/internal/k8s"
	networking "github.com/numtide/go2nix/torture/internal/networking"
	observability "github.com/numtide/go2nix/torture/internal/observability"
	testinglib "github.com/numtide/go2nix/torture/internal/testing"
	web "github.com/numtide/go2nix/torture/internal/web"
)

func main() {
	if err := common.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "common.Run: %v\n", err)
		os.Exit(1)
	}
	if err := aws.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "aws.Run: %v\n", err)
		os.Exit(1)
	}
	if err := gcp.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "gcp.Run: %v\n", err)
		os.Exit(1)
	}
	if err := azure.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "azure.Run: %v\n", err)
		os.Exit(1)
	}
	if err := k8s.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "k8s.Run: %v\n", err)
		os.Exit(1)
	}
	if err := web.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "web.Run: %v\n", err)
		os.Exit(1)
	}
	if err := db.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "db.Run: %v\n", err)
		os.Exit(1)
	}
	if err := observability.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "observability.Run: %v\n", err)
		os.Exit(1)
	}
	if err := cryptolib.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "cryptolib.Run: %v\n", err)
		os.Exit(1)
	}
	if err := data.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "data.Run: %v\n", err)
		os.Exit(1)
	}
	if err := networking.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "networking.Run: %v\n", err)
		os.Exit(1)
	}
	if err := testinglib.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "testinglib.Run: %v\n", err)
		os.Exit(1)
	}
	if err := conflicta.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "conflicta.Run: %v\n", err)
		os.Exit(1)
	}
	if err := conflictb.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "conflictb.Run: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("ok")
}
