// Code generated by generator; DO NOT EDIT.

package common

import (
	"encoding/csv"
	"encoding/json"
	"encoding/xml"

	btoml "github.com/BurntSushi/toml"
	goenv "github.com/Netflix/go-env"
	"github.com/alecthomas/kong"
	envparse "github.com/caarlos0/env/v11"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/fatih/color"
	cbor "github.com/fxamacker/cbor/v2"
	gojson "github.com/goccy/go-json"
	"github.com/ilyakaznacheev/cleanenv"
	goflags "github.com/jessevdk/go-flags"
	"github.com/joho/godotenv"
	"github.com/kelseyhightower/envconfig"
	"github.com/klauspost/compress/zstd"
	koanf "github.com/knadh/koanf/v2"
	"github.com/manifoldco/promptui"
	hashstructure "github.com/mitchellh/hashstructure/v2"
	"github.com/muesli/termenv"
	toml "github.com/pelletier/go-toml/v2"
	progressbar "github.com/schollz/progressbar/v3"
	msgpack2 "github.com/shamaton/msgpack/v2"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	cli "github.com/urfave/cli/v2"
	msgpack "github.com/vmihailenco/msgpack/v5"
	yaml "gopkg.in/yaml.v3"
)

// Run exercises imported packages.
func Run() error {
	_ = godotenv.Load
	_ = envconfig.Process
	_ = koanf.New(".")
	_ = goenv.UnmarshalFromEnviron
	_ = cleanenv.ReadEnv
	_ = envparse.Parse
	var _ *json.Decoder
	var _ *toml.Decoder
	var _ *yaml.Decoder
	var _ *msgpack.Decoder
	_ = cbor.DecOptions{}
	var _ *btoml.Decoder
	var _ *gojson.Decoder
	var _ *xml.Decoder
	var _ *csv.Reader
	var _ *zstd.Decoder
	_ = hashstructure.FormatV2
	_ = msgpack2.Marshal
	_ = cobra.Command{}
	_ = viper.New()
	_ = cli.App{}
	var _ tea.Model
	_ = lipgloss.NewStyle()
	_ = color.New()
	_ = progressbar.Default(100)
	_ = promptui.Prompt{}
	_ = termenv.ColorProfile()
	var _ *kong.Context
	var _ *goflags.Parser
	return nil
}
