// Code generated by generator; DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	aws "github.com/numtide/go2nix/torture/internal/aws"
	common "github.com/numtide/go2nix/torture/internal/common"
	conflicta "github.com/numtide/go2nix/torture/internal/conflict-a"
	cryptolib "github.com/numtide/go2nix/torture/internal/crypto"
	db "github.com/numtide/go2nix/torture/internal/db"
)

func main() {
	if err := common.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "common.Run: %v\n", err)
		os.Exit(1)
	}
	if err := aws.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "aws.Run: %v\n", err)
		os.Exit(1)
	}
	if err := db.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "db.Run: %v\n", err)
		os.Exit(1)
	}
	if err := cryptolib.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "cryptolib.Run: %v\n", err)
		os.Exit(1)
	}
	if err := conflicta.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "conflicta.Run: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("ok")
}
